# Generated by Django 5.0 on 2026-01-09 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='JWT token with Bearer prefix')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiration time')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Authentication Token',
                'verbose_name_plural': 'Authentication Tokens',
                'db_table': 'clickpesa_auth_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.CharField(help_text='ClickPesa transaction ID', max_length=255, primary_key=True, serialize=False)),
                ('order_reference', models.CharField(db_index=True, help_text='Unique order reference', max_length=255, unique=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment reference from provider', max_length=255, null=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'PROCESSING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('SETTLED', 'SETTLED'), ('PENDING', 'PENDING')], default='PROCESSING', max_length=20)),
                ('channel', models.CharField(default='MOBILE MONEY', max_length=50)),
                ('channel_provider', models.CharField(blank=True, help_text='e.g., TIGO-PESA, M-PESA', max_length=100, null=True)),
                ('collected_amount', models.DecimalField(decimal_places=2, help_text='Amount collected', max_digits=12)),
                ('collected_currency', models.CharField(default='TZS', max_length=3)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, help_text='Status message', null=True)),
                ('raw_response', models.JSONField(blank=True, help_text='Full API response', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clickpesa_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'clickpesa_payment_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_reference'], name='clickpesa_p_order_r_80cb31_idx'), models.Index(fields=['status'], name='clickpesa_p_status_966fde_idx'), models.Index(fields=['customer_phone'], name='clickpesa_p_custome_e8b239_idx'), models.Index(fields=['-created_at'], name='clickpesa_p_created_2e3763_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayoutTransaction',
            fields=[
                ('id', models.CharField(help_text='ClickPesa payout ID', max_length=255, primary_key=True, serialize=False)),
                ('order_reference', models.CharField(db_index=True, help_text='Unique order reference', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('AUTHORIZED', 'AUTHORIZED'), ('SUCCESS', 'SUCCESS'), ('REVERSED', 'REVERSED'), ('REFUNDED', 'REFUNDED'), ('PROCESSING', 'PROCESSING'), ('PENDING', 'PENDING'), ('FAILED', 'FAILED')], default='PROCESSING', max_length=20)),
                ('channel', models.CharField(default='MOBILE MONEY', max_length=50)),
                ('channel_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('transfer_type', models.CharField(blank=True, help_text='ACH or RTGS for bank transfers', max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount deducted (includes fee)', max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('fee', models.DecimalField(decimal_places=2, default=0, help_text='Transaction fee', max_digits=12)),
                ('beneficiary_amount', models.DecimalField(decimal_places=2, help_text='Amount beneficiary receives', max_digits=12)),
                ('exchanged', models.BooleanField(default=False)),
                ('source_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('target_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('source_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('beneficiary_account_number', models.CharField(help_text='Phone number or account number', max_length=100)),
                ('beneficiary_account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary_mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('beneficiary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('beneficiary_swift_number', models.CharField(blank=True, max_length=50, null=True)),
                ('beneficiary_routing_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, help_text='Full API response', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clickpesa_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payout Transaction',
                'verbose_name_plural': 'Payout Transactions',
                'db_table': 'clickpesa_payout_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_reference'], name='clickpesa_p_order_r_184342_idx'), models.Index(fields=['status'], name='clickpesa_p_status_7db43f_idx'), models.Index(fields=['beneficiary_account_number'], name='clickpesa_p_benefic_6f86a9_idx'), models.Index(fields=['-created_at'], name='clickpesa_p_created_5c510d_idx')],
            },
        ),
    ]
