# Generated by Django 4.2.28 on 2026-02-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickpesa', '0002_wallet_wallettransaction_escrowtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional project-specific metadata'),
        ),
        migrations.AddField(
            model_name='payouttransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional project-specific metadata'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['content_type', 'object_id'], name='clickpesa_e_content_c45f15_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['status'], name='clickpesa_e_status_cd1bae_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['auto_release_date'], name='clickpesa_e_auto_re_2a6118_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['content_type', 'object_id'], name='clickpesa_w_content_73185e_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['reference'], name='clickpesa_w_referen_9544f9_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type'], name='clickpesa_w_transac_10bc55_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['status'], name='clickpesa_w_status_0ad748_idx'),
        ),
    ]
